{ pkgs, treefmt-nix }:
let
  # Evaluate the shared treefmt-nix module once and reuse the generated config
  # file plus the formatter packages it enables. This keeps the command runners
  # and the flake-parts module on the same preset without copying formatter
  # lists around.
  presetEval = treefmt-nix.lib.evalModule pkgs {
    imports = [
      ./preset.nix
    ];

    # The standalone commands choose a runtime root explicitly. Leaving the
    # treefmt-nix wrapper to infer from the generated store config would make
    # /nix/store the tree root.
    projectRootFile = null;
  };

  inherit (presetEval.config.build) configFile;

  # treefmt-nix exposes the actual formatter packages through build.programs.
  # Adding them to runtimeInputs means the generated shell applications can run
  # `nixfmt`, `prettier`, `ruff`, etc. without users installing those tools
  # separately.
  formatterPackages = builtins.attrValues presetEval.config.build.programs;
  runtimeInputs = [
    pkgs.git
    pkgs.treefmt
  ]
  ++ formatterPackages;

  # Shared implementation for commands that should ignore local treefmt.toml
  # and always run the preset config generated above.
  #
  # We intentionally do not use treefmt-nix's build.wrapper here. That wrapper
  # points treefmt at a generated config in /nix/store; for a global command that
  # would make treefmt treat /nix/store as the tree root. Instead, we pass both
  # the generated config and an explicit runtime tree root.
  presetScript = ''
    resolve_preset_root() {
      # Manual override for unusual cases, scripts, or editor integrations.
      if [ -n "''${TREEFMT_PRESET_ROOT:-}" ]; then
        printf '%s\n' "$TREEFMT_PRESET_ROOT"
        return
      fi

      # `nix fmt` sets PRJ_ROOT to the nearest flake root. Respect it so this
      # package also works as this flake's own formatter output.
      if [ -n "''${PRJ_ROOT:-}" ] && [ -d "$PRJ_ROOT" ]; then
        printf '%s\n' "$PRJ_ROOT"
        return
      fi

      # For normal shell use, formatting an entire git worktree is the least
      # surprising default when the command is run from a subdirectory.
      if git_root="$(git rev-parse --show-toplevel 2>/dev/null)"; then
        printf '%s\n' "$git_root"
        return
      fi

      # Last resort for ad-hoc directories that are not inside git.
      pwd
    }

    tree_root="$(resolve_preset_root)"

    exec treefmt \
      --config-file=${configFile} \
      --tree-root "$tree_root" \
      "$@"
  '';

  mkPresetRunner =
    name:
    pkgs.writeShellApplication {
      inherit name runtimeInputs;
      text = presetScript;
    };
in
rec {
  treefmt-preset-helper = pkgs.writeShellApplication {
    name = "treefmt-preset-helper";
    runtimeInputs = [ pkgs.coreutils ];
    text = ''
      cat <<'EOF'
      treefmt-preset command guide

      This flake exposes several commands. They intentionally do different
      things, so pick the one that matches how you want formatting to work.

      Commands:

        treefmt-preset-helper
          Print this guide. This is the default package and app, so plain
          `nix run github:sshawn9/treefmt-preset` is informational and will not
          modify files.

        treefmt-preset
          Always use the bundled preset generated by treefmt-nix.
          It does not read local treefmt.toml or .treefmt.toml.

          Run:
            nix run github:sshawn9/treefmt-preset#treefmt-preset

        treefmt-auto
          If the current directory or one of its parents has treefmt.toml or
          .treefmt.toml, run upstream treefmt with that local config.
          Otherwise, fall back to treefmt-preset.

          Run:
            nix run github:sshawn9/treefmt-preset#treefmt-auto

        treefmt
          Upstream treefmt unchanged. It keeps native treefmt behavior and does
          not load this preset.

          Run:
            nix run github:sshawn9/treefmt-preset#treefmt -- --help

        treefmt-preset-export-config
          Copy the generated preset config to ./.treefmt.toml so you can inspect
          it, edit it, or use it with upstream treefmt.
          The exported file is the real treefmt-nix output, so formatter
          commands may point at /nix/store paths.

          Run:
            nix run github:sshawn9/treefmt-preset#treefmt-preset-export-config

          Options:
            --force   overwrite an existing .treefmt.toml
            --stdout  print the generated config instead of writing a file
            --help    print command help

      Project integration:

        Flake-parts projects:
          imports = [ inputs.treefmt-preset.flakeModules.treefmt-preset ];

        NixOS:
          imports = [ inputs.treefmt-preset.nixosModules.default ];

        nix-darwin:
          imports = [ inputs.treefmt-preset.darwinModules.default ];

        Home Manager:
          imports = [ inputs.treefmt-preset.homeModules.default ];
      EOF
    '';
  };

  # Main command: stable preset, no local config lookup.
  treefmt-preset = mkPresetRunner "treefmt-preset";

  treefmt-preset-export-config = pkgs.writeShellApplication {
    name = "treefmt-preset-export-config";
    runtimeInputs = [ pkgs.coreutils ];
    text = ''
      usage() {
        cat <<'EOF'
      Usage: treefmt-preset-export-config [--force] [--stdout] [--help]

      Write the generated treefmt-preset config to ./.treefmt.toml.

      Options:
        -f, --force   overwrite an existing .treefmt.toml
        --stdout      print the generated config instead of writing a file
        -h, --help    show this help
      EOF
      }

      force=0
      stdout=0

      while [ "$#" -gt 0 ]; do
        case "$1" in
          -f|--force)
            force=1
            ;;
          --stdout)
            stdout=1
            ;;
          -h|--help)
            usage
            exit 0
            ;;
          *)
            printf 'treefmt-preset-export-config: unknown argument: %s\n' "$1" >&2
            usage >&2
            exit 2
            ;;
        esac
        shift
      done

      if [ "$stdout" -eq 1 ]; then
        cat ${configFile}
        exit 0
      fi

      target=.treefmt.toml

      if [ -e "$target" ] && [ "$force" -ne 1 ]; then
        printf 'treefmt-preset-export-config: %s already exists\n' "$target" >&2
        printf 'Use --force to overwrite it, or --stdout to inspect the generated config.\n' >&2
        exit 1
      fi

      cp ${configFile} "$target"
      printf 'Wrote %s/%s\n' "$PWD" "$target"
    '';
  };

  # Expose upstream treefmt unchanged. A package named `treefmt` should not hide
  # preset-specific behavior; users should be able to rely on native treefmt
  # config discovery and CLI semantics here.
  inherit (pkgs) treefmt;

  # Hybrid command: prefer a repository's own treefmt.toml when it has one, but
  # still be useful in directories with no local config.
  treefmt-auto = pkgs.writeShellApplication {
    name = "treefmt-auto";
    inherit runtimeInputs;
    text = ''
      find_local_config() {
        dir="$PWD"

        while true; do
          if [ -f "$dir/treefmt.toml" ] || [ -f "$dir/.treefmt.toml" ]; then
            return 0
          fi

          if [ "$dir" = / ]; then
            return 1
          fi

          dir="$(dirname "$dir")"
        done
      }

      # TREEFMT_CONFIG is treefmt's native explicit config override. If a user
      # set it, pass through to plain treefmt instead of forcing the preset.
      if [ -n "''${TREEFMT_CONFIG:-}" ] || find_local_config; then
        exec treefmt "$@"
      fi

      ${presetScript}
    '';
  };

  default = treefmt-preset-helper;
}
